services:
  mongo:
    image: mongodb/mongodb-community-server
    ports:
      - '27017:27017'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: pluralsight
      POSTGRES_PASSWORD: pluralsight
    ports:
      - '5432:5432'